# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY requirements.txt .
COPY app.py .
COPY templates/ templates/

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto
EXPOSE 5000

# Usar Gunicorn como servidor
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]