name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecuta el pipeline cuando hay un push a la rama main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Instala pytest para ejecutar tests
    
    - name: Install bandit
      run: |
         python -m pip install --upgrade pip  # Corregido
         pip install bandit

    - name: Run bandit
      run: |
        bandit -r .

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        pytest tests/  # Ejecuta los tests en la carpeta tests/

  build-and-push:
    needs: test  # Este job depende del job "test"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t elfer/app-image:latest -f Dockerfile.app .

    - name: Push Docker image
      run: docker push elfer/app-image:latest